# Generated by Django 2.2 on 2020-10-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now=True)),
                ('Title', models.CharField(max_length=255, unique=True)),
                ('Details', models.TextField(unique=True)),
                ('NewsFrom', models.CharField(max_length=40)),
                ('URL', models.URLField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
